from typing import Any, Iterator

__version__: str


class Search:
    def __iter__(self) -> Iterator[dict[str, Any]]: ...
    def to_geojson(self) -> dict[str, Any]: ...
    def matched(self) -> int: ...
    def items(self) -> list[dict[str, Any]]: ...
    def item_collection_as_dict(self) -> dict[str, Any]: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    def __len__(self) -> int: ...

class Client:
    def __init__(
        self,
        config: dict[str, Any] | None = None,
        *,
        catalogs: list[dict[str, Any]] | None = None,
        providers: list[dict[str, Any]] | None = None,
        settings: dict[str, Any] | None = None,
        storage: str = "memory",
    ) -> None: ...
    @classmethod
    def open(
        cls,
        url: str,
        *,
        id: str | None = None,
        storage: str = "memory",
    ) -> "Client": ...
    @classmethod
    def from_yaml(cls, yaml_path: str, *, storage: str = "memory") -> "Client": ...

    # engine lifecycle
    def start(self) -> None: ...
    def shutdown(self) -> None: ...

    # catalogs
    def add_catalog(
        self, catalog: dict[str, Any], *, provider: str | None = None
    ) -> dict[str, Any]: ...
    def add_catalogs(
        self, catalogs: list[dict[str, Any]]
    ) -> list[dict[str, Any]]: ...
    def get_catalog(self, id: str) -> dict[str, Any]: ...
    def list_catalogs(self) -> list[dict[str, Any]]: ...
    def update_catalog(self, id: str, update: dict[str, Any]) -> dict[str, Any]: ...
    def delete_catalog(self, id: str) -> None: ...

    # providers
    def add_provider(self, provider: dict[str, Any]) -> dict[str, Any]: ...
    def add_providers(
        self, providers: list[dict[str, Any]]
    ) -> list[dict[str, Any]]: ...
    def get_provider(self, id: str) -> dict[str, Any]: ...
    def list_providers(self) -> list[dict[str, Any]]: ...
    def update_provider(self, id: str, update: dict[str, Any]) -> dict[str, Any]: ...
    def delete_provider(self, id: str) -> None: ...

    # settings
    def get_settings(self) -> dict[str, Any]: ...
    def update_settings(self, update: dict[str, Any]) -> None: ...

    # search & discovery (sync)
    def search(self, **kwargs: Any) -> Search: ...
    def list_collections(self) -> list[dict[str, Any]]: ...
    def get_collections(self) -> list[dict[str, Any]]: ...
    def get_collection(self, id: str) -> dict[str, Any]: ...
    def catalogs_supporting(self, collection_id: str) -> list[str]: ...
    def collections_by_catalog(self) -> dict[str, list[str]]: ...
    def describe_collection(
        self, catalog_id: str, collection_id: str
    ) -> dict[str, Any] | None: ...

class AsyncClient:
    def __init__(
        self,
        config: dict[str, Any] | None = None,
        *,
        catalogs: list[dict[str, Any]] | None = None,
        providers: list[dict[str, Any]] | None = None,
        settings: dict[str, Any] | None = None,
        storage: str = "memory",
    ) -> None: ...
    @classmethod
    async def open(
        cls,
        url: str,
        *,
        id: str | None = None,
        storage: str = "memory",
    ) -> "AsyncClient": ...
    @classmethod
    def from_yaml(
        cls, yaml_path: str, *, storage: str = "memory"
    ) -> "AsyncClient": ...

    # engine lifecycle
    async def start(self) -> None: ...
    async def shutdown(self) -> None: ...

    # catalogs (sync — config-time operations)
    def add_catalog(
        self, catalog: dict[str, Any], *, provider: str | None = None
    ) -> dict[str, Any]: ...
    def add_catalogs(
        self, catalogs: list[dict[str, Any]]
    ) -> list[dict[str, Any]]: ...
    def get_catalog(self, id: str) -> dict[str, Any]: ...
    def list_catalogs(self) -> list[dict[str, Any]]: ...
    def update_catalog(self, id: str, update: dict[str, Any]) -> dict[str, Any]: ...
    def delete_catalog(self, id: str) -> None: ...

    # providers (sync)
    def add_provider(self, provider: dict[str, Any]) -> dict[str, Any]: ...
    def add_providers(
        self, providers: list[dict[str, Any]]
    ) -> list[dict[str, Any]]: ...
    def get_provider(self, id: str) -> dict[str, Any]: ...
    def list_providers(self) -> list[dict[str, Any]]: ...
    def update_provider(self, id: str, update: dict[str, Any]) -> dict[str, Any]: ...
    def delete_provider(self, id: str) -> None: ...

    # settings (sync)
    def get_settings(self) -> dict[str, Any]: ...
    def update_settings(self, update: dict[str, Any]) -> None: ...

    # search & discovery (async)
    async def search(self, **kwargs: Any) -> Search: ...
    async def list_collections(self) -> list[dict[str, Any]]: ...
    async def get_collections(self) -> list[dict[str, Any]]: ...
    async def get_collection(self, id: str) -> dict[str, Any]: ...
    async def catalogs_supporting(self, collection_id: str) -> list[str]: ...
    async def collections_by_catalog(self) -> dict[str, list[str]]: ...
    async def describe_collection(
        self, catalog_id: str, collection_id: str
    ) -> dict[str, Any] | None: ...
